{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "MediaServicesManagementClient",
    "description" : "Media Services resource management APIs.",
    "version" : "2015-10-01"
  },
  "servers" : [ {
    "url" : "https://management.azure.com/"
  } ],
  "security" : [ {
    "azure_auth" : [ "user_impersonation" ]
  } ],
  "paths" : {
    "/providers/Microsoft.Media/operations" : {
      "get" : {
        "description" : "Lists all of the available Media Services REST API operations.",
        "externalDocs" : {
          "url" : "https://aka.ms/media-manage"
        },
        "operationId" : "Operations_List",
        "parameters" : [ {
          "name" : "api-version",
          "in" : "query",
          "description" : "Version of the API to be used with the client request. The current version is 2015-10-01.",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Success. Returns a list of operations.",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/OperationListResult"
                }
              }
            }
          }
        }
      }
    },
    "/subscriptions/{subscriptionId}/providers/Microsoft.Media/CheckNameAvailability" : {
      "post" : {
        "description" : "Checks whether the Media Service resource name is available. The name must be globally unique.",
        "externalDocs" : {
          "url" : "https://aka.ms/media-manage"
        },
        "operationId" : "MediaService_CheckNameAvailability",
        "parameters" : [ {
          "name" : "subscriptionId",
          "in" : "path",
          "description" : "The unique identifier for a Microsoft Azure subscription.",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "api-version",
          "in" : "query",
          "description" : "Version of the API to be used with the client request. The current version is 2015-10-01.",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        } ],
        "requestBody" : {
          "description" : "Properties needed to check the availability of a name.",
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/CheckNameAvailabilityInput"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "Success. Returns details about whether a Media Service resource name is available.",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/CheckNameAvailabilityOutput"
                },
                "example" : {
                  "message" : "Already in use by another Media Service instance. Please try again with a name that is not likely to be in use.",
                  "nameAvailable" : false,
                  "reason" : "AlreadyExists"
                }
              }
            }
          },
          "default" : {
            "description" : "CheckNameAvailability of a Media Service failed.",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/ApiError"
                }
              }
            }
          }
        }
      }
    },
    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Media/mediaservices" : {
      "get" : {
        "description" : "Lists all of the Media Services in a resource group.",
        "externalDocs" : {
          "url" : "https://aka.ms/media-manage"
        },
        "operationId" : "MediaService_ListByResourceGroup",
        "parameters" : [ {
          "name" : "subscriptionId",
          "in" : "path",
          "description" : "The unique identifier for a Microsoft Azure subscription.",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "api-version",
          "in" : "query",
          "description" : "Version of the API to be used with the client request. The current version is 2015-10-01.",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "resourceGroupName",
          "in" : "path",
          "description" : "Name of the resource group within the Azure subscription.",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Success. Returns a list of all of the Media Services accounts in a resource group.",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/MediaServiceCollection"
                },
                "example" : {
                  "value" : [ {
                    "id" : "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/contosoresources/providers/Microsoft.Media/mediaservices/contosomedia",
                    "location" : "West US",
                    "name" : "contosomedia",
                    "properties" : {
                      "apiEndpoints" : [ {
                        "endpoint" : "https://wamsbayclus001rest-hs.cloudapp.net/api/",
                        "majorVersion" : "2"
                      } ],
                      "storageAccounts" : [ {
                        "id" : "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/contosoresources/providers/Microsoft.Storage/storageAccounts/contosomedia",
                        "isPrimary" : true
                      } ]
                    },
                    "type" : "Microsoft.Media/mediaservices"
                  } ]
                }
              }
            }
          },
          "default" : {
            "description" : "List Media Services failed.",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/ApiError"
                }
              }
            }
          }
        }
      }
    },
    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Media/mediaservices/{mediaServiceName}" : {
      "get" : {
        "description" : "Gets a Media Service.",
        "externalDocs" : {
          "url" : "https://aka.ms/media-manage"
        },
        "operationId" : "MediaService_Get",
        "parameters" : [ {
          "name" : "subscriptionId",
          "in" : "path",
          "description" : "The unique identifier for a Microsoft Azure subscription.",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "api-version",
          "in" : "query",
          "description" : "Version of the API to be used with the client request. The current version is 2015-10-01.",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "resourceGroupName",
          "in" : "path",
          "description" : "Name of the resource group within the Azure subscription.",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "mediaServiceName",
          "in" : "path",
          "description" : "Name of the Media Service.",
          "required" : true,
          "schema" : {
            "maxLength" : 24,
            "minLength" : 3,
            "pattern" : "^[a-z0-9]{3,24}$",
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Success. Returns the details of the Media Services account.",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/MediaService"
                },
                "example" : {
                  "id" : "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/contosoresources/providers/Microsoft.Media/mediaservices/contosomedia",
                  "location" : "West US",
                  "name" : "contosomedia",
                  "properties" : {
                    "apiEndpoints" : [ {
                      "endpoint" : "https://wamsbayclus001rest-hs.cloudapp.net/api/",
                      "majorVersion" : "2"
                    } ],
                    "storageAccounts" : [ {
                      "id" : "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/contosoresources/providers/Microsoft.Storage/storageAccounts/contosomedia",
                      "isPrimary" : true
                    } ]
                  },
                  "type" : "Microsoft.Media/mediaservices"
                }
              }
            }
          },
          "default" : {
            "description" : "Get Media Services failed.",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/ApiError"
                }
              }
            }
          }
        }
      },
      "put" : {
        "description" : "Creates a Media Service.",
        "externalDocs" : {
          "url" : "https://aka.ms/media-manage"
        },
        "operationId" : "MediaService_Create",
        "parameters" : [ {
          "name" : "subscriptionId",
          "in" : "path",
          "description" : "The unique identifier for a Microsoft Azure subscription.",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "api-version",
          "in" : "query",
          "description" : "Version of the API to be used with the client request. The current version is 2015-10-01.",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "resourceGroupName",
          "in" : "path",
          "description" : "Name of the resource group within the Azure subscription.",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "mediaServiceName",
          "in" : "path",
          "description" : "Name of the Media Service.",
          "required" : true,
          "schema" : {
            "maxLength" : 24,
            "minLength" : 3,
            "pattern" : "^[a-z0-9]{3,24}$",
            "type" : "string"
          }
        } ],
        "requestBody" : {
          "description" : "Media Service properties needed for creation.",
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/MediaService"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "201" : {
            "description" : "Success. Returns the new Media Services account.",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/MediaService"
                },
                "example" : {
                  "id" : "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/contosoresources/providers/Microsoft.Media/mediaservices/contosomedia",
                  "location" : "West US",
                  "name" : "contosomedia",
                  "properties" : {
                    "apiEndpoints" : [ {
                      "endpoint" : "https://wamsbayclus001rest-hs.cloudapp.net/api/",
                      "majorVersion" : "2"
                    } ],
                    "storageAccounts" : [ {
                      "id" : "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/contosoresources/providers/Microsoft.Storage/storageAccounts/contosomedia",
                      "isPrimary" : true
                    } ]
                  },
                  "type" : "Microsoft.Media/mediaservices"
                }
              }
            }
          },
          "default" : {
            "description" : "Create Media Services failed.",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/ApiError"
                }
              }
            }
          }
        }
      },
      "delete" : {
        "description" : "Deletes a Media Service.",
        "externalDocs" : {
          "url" : "https://aka.ms/media-manage"
        },
        "operationId" : "MediaService_Delete",
        "parameters" : [ {
          "name" : "subscriptionId",
          "in" : "path",
          "description" : "The unique identifier for a Microsoft Azure subscription.",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "api-version",
          "in" : "query",
          "description" : "Version of the API to be used with the client request. The current version is 2015-10-01.",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "resourceGroupName",
          "in" : "path",
          "description" : "Name of the resource group within the Azure subscription.",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "mediaServiceName",
          "in" : "path",
          "description" : "Name of the Media Service.",
          "required" : true,
          "schema" : {
            "maxLength" : 24,
            "minLength" : 3,
            "pattern" : "^[a-z0-9]{3,24}$",
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Success. The Media Services account was deleted."
          },
          "204" : {
            "description" : "No Content. The account name does not exist."
          },
          "default" : {
            "description" : "Delete Media Services failed.",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/ApiError"
                }
              }
            }
          }
        }
      },
      "patch" : {
        "description" : "Updates a Media Service.",
        "externalDocs" : {
          "url" : "https://aka.ms/media-manage"
        },
        "operationId" : "MediaService_Update",
        "parameters" : [ {
          "name" : "subscriptionId",
          "in" : "path",
          "description" : "The unique identifier for a Microsoft Azure subscription.",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "api-version",
          "in" : "query",
          "description" : "Version of the API to be used with the client request. The current version is 2015-10-01.",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "resourceGroupName",
          "in" : "path",
          "description" : "Name of the resource group within the Azure subscription.",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "mediaServiceName",
          "in" : "path",
          "description" : "Name of the Media Service.",
          "required" : true,
          "schema" : {
            "maxLength" : 24,
            "minLength" : 3,
            "pattern" : "^[a-z0-9]{3,24}$",
            "type" : "string"
          }
        } ],
        "requestBody" : {
          "description" : "Media Service properties needed for update.",
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/MediaService"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "Success. The Media Services account was updated.",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/MediaService"
                },
                "example" : {
                  "id" : "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/contosoresources/providers/Microsoft.Media/mediaservices/contosomedia",
                  "location" : "West US",
                  "name" : "contosomedia",
                  "properties" : {
                    "apiEndpoints" : [ {
                      "endpoint" : "https://wamsbayclus001rest-hs.cloudapp.net/api/",
                      "majorVersion" : "2"
                    } ],
                    "storageAccounts" : [ {
                      "id" : "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/contosoresources/providers/Microsoft.Storage/storageAccounts/contosomedia",
                      "isPrimary" : true
                    } ]
                  },
                  "type" : "Microsoft.Media/mediaservices"
                }
              }
            }
          },
          "default" : {
            "description" : "Update Media Services failed.",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/ApiError"
                }
              }
            }
          }
        }
      }
    },
    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Media/mediaservices/{mediaServiceName}/listKeys" : {
      "post" : {
        "description" : "Lists the keys for a Media Service.",
        "externalDocs" : {
          "url" : "https://aka.ms/media-manage"
        },
        "operationId" : "MediaService_ListKeys",
        "parameters" : [ {
          "name" : "subscriptionId",
          "in" : "path",
          "description" : "The unique identifier for a Microsoft Azure subscription.",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "api-version",
          "in" : "query",
          "description" : "Version of the API to be used with the client request. The current version is 2015-10-01.",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "resourceGroupName",
          "in" : "path",
          "description" : "Name of the resource group within the Azure subscription.",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "mediaServiceName",
          "in" : "path",
          "description" : "Name of the Media Service.",
          "required" : true,
          "schema" : {
            "maxLength" : 24,
            "minLength" : 3,
            "pattern" : "^[a-z0-9]{3,24}$",
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Success. The keys for the Media Services account were listed.",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/ServiceKeys"
                },
                "example" : {
                  "primaryAuthEndpoint" : "https://wamsprodglobal001acs.accesscontrol.windows.net/",
                  "primaryKey" : "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=",
                  "scope" : "urn:windowsazuremediaservices",
                  "secondaryAuthEndpoint" : "https://wamsprodglobal002acs.accesscontrol.windows.net/",
                  "secondaryKey" : "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx="
                }
              }
            }
          },
          "default" : {
            "description" : "List Media Service keys failed.",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/ApiError"
                }
              }
            }
          }
        }
      }
    },
    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Media/mediaservices/{mediaServiceName}/regenerateKey" : {
      "post" : {
        "description" : "Regenerates a primary or secondary key for a Media Service.",
        "externalDocs" : {
          "url" : "https://aka.ms/media-manage"
        },
        "operationId" : "MediaService_RegenerateKey",
        "parameters" : [ {
          "name" : "subscriptionId",
          "in" : "path",
          "description" : "The unique identifier for a Microsoft Azure subscription.",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "api-version",
          "in" : "query",
          "description" : "Version of the API to be used with the client request. The current version is 2015-10-01.",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "resourceGroupName",
          "in" : "path",
          "description" : "Name of the resource group within the Azure subscription.",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "mediaServiceName",
          "in" : "path",
          "description" : "Name of the Media Service.",
          "required" : true,
          "schema" : {
            "maxLength" : 24,
            "minLength" : 3,
            "pattern" : "^[a-z0-9]{3,24}$",
            "type" : "string"
          }
        } ],
        "requestBody" : {
          "description" : "Properties needed to regenerate the Media Service key.",
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/RegenerateKeyInput"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "Success. The Media Services key specified in the input was regenerated.",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/RegenerateKeyOutput"
                },
                "example" : {
                  "key" : "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx="
                }
              }
            }
          },
          "default" : {
            "description" : "Regenerate Media Service key failed.",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/ApiError"
                }
              }
            }
          }
        }
      }
    },
    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Media/mediaservices/{mediaServiceName}/syncStorageKeys" : {
      "post" : {
        "description" : "Synchronizes storage account keys for a storage account associated with the Media Service account.",
        "externalDocs" : {
          "url" : "https://aka.ms/media-manage"
        },
        "operationId" : "MediaService_SyncStorageKeys",
        "parameters" : [ {
          "name" : "subscriptionId",
          "in" : "path",
          "description" : "The unique identifier for a Microsoft Azure subscription.",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "api-version",
          "in" : "query",
          "description" : "Version of the API to be used with the client request. The current version is 2015-10-01.",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "resourceGroupName",
          "in" : "path",
          "description" : "Name of the resource group within the Azure subscription.",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "mediaServiceName",
          "in" : "path",
          "description" : "Name of the Media Service.",
          "required" : true,
          "schema" : {
            "maxLength" : 24,
            "minLength" : 3,
            "pattern" : "^[a-z0-9]{3,24}$",
            "type" : "string"
          }
        } ],
        "requestBody" : {
          "description" : "Properties needed to synchronize the keys for a storage account to the Media Service.",
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/SyncStorageKeysInput"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "Success. The keys for the storage account were synchronized."
          },
          "default" : {
            "description" : "Synch Media Service storage keys failed.",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/ApiError"
                }
              }
            }
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "ApiEndpoint" : {
        "type" : "object",
        "properties" : {
          "endpoint" : {
            "type" : "string",
            "description" : "The Media Services REST endpoint."
          },
          "majorVersion" : {
            "type" : "string",
            "description" : "The version of Media Services REST API."
          }
        },
        "description" : "The properties for a Media Services REST API endpoint.",
        "example" : {
          "endpoint" : "https://wamsbayclus001rest-hs.cloudapp.net/api/",
          "majorVersion" : "2"
        }
      },
      "ApiError" : {
        "type" : "object",
        "properties" : {
          "code" : {
            "type" : "string",
            "description" : "Error code."
          },
          "message" : {
            "type" : "string",
            "description" : "Error message."
          }
        },
        "description" : "The error returned from a failed Media Services REST API call.",
        "example" : {
          "error" : {
            "code" : "BadRequest",
            "message" : "Name availability check is not supported for type Microsoft.Media/mediaservices."
          }
        }
      },
      "CheckNameAvailabilityInput" : {
        "required" : [ "name", "type" ],
        "type" : "object",
        "properties" : {
          "name" : {
            "maxLength" : 24,
            "minLength" : 3,
            "pattern" : "^[a-z0-9]{3,24}$",
            "type" : "string",
            "description" : "The name of the resource. A name must be globally unique."
          },
          "type" : {
            "$ref" : "#/components/schemas/ResourceType"
          }
        },
        "description" : "The request body for CheckNameAvailability API.",
        "example" : {
          "name" : "contosomedia",
          "type" : "mediaservices"
        }
      },
      "CheckNameAvailabilityOutput" : {
        "type" : "object",
        "properties" : {
          "message" : {
            "type" : "string",
            "description" : "Specifies the detailed reason if the name is not available."
          },
          "nameAvailable" : {
            "type" : "boolean",
            "description" : "Specifies if the name is available."
          },
          "reason" : {
            "type" : "string",
            "description" : "Specifies the reason if the name is not available.",
            "enum" : [ "None", "Invalid", "AlreadyExists" ]
          }
        },
        "description" : "The response body for CheckNameAvailability API."
      },
      "MediaService" : {
        "properties" : {
          "properties" : {
            "$ref" : "#/components/schemas/MediaServiceProperties"
          }
        },
        "description" : "The properties of a Media Service resource.",
        "allOf" : [ {
          "$ref" : "#/components/schemas/Resource"
        } ]
      },
      "MediaServiceCollection" : {
        "type" : "object",
        "properties" : {
          "value" : {
            "type" : "array",
            "description" : "The collection of Media Service resources.",
            "items" : {
              "$ref" : "#/components/schemas/MediaService"
            }
          }
        },
        "description" : "The collection of Media Service resources."
      },
      "MediaServiceProperties" : {
        "type" : "object",
        "properties" : {
          "apiEndpoints" : {
            "type" : "array",
            "description" : "Read-only property that lists the Media Services REST API endpoints for this resource. If supplied on a PUT or PATCH, the value will be ignored.",
            "readOnly" : true,
            "items" : {
              "$ref" : "#/components/schemas/ApiEndpoint"
            }
          },
          "storageAccounts" : {
            "type" : "array",
            "description" : "The storage accounts for this resource.",
            "items" : {
              "$ref" : "#/components/schemas/StorageAccount"
            }
          }
        },
        "description" : "The additional properties of a Media Service resource."
      },
      "Operation" : {
        "type" : "object",
        "properties" : {
          "display" : {
            "type" : "object",
            "properties" : {
              "operation" : {
                "type" : "string",
                "description" : "Operation type: Read, write, delete, etc.",
                "readOnly" : true
              },
              "provider" : {
                "type" : "string",
                "description" : "Service provider: Microsoft.Media",
                "readOnly" : true
              },
              "resource" : {
                "type" : "string",
                "description" : "Resource on which the operation is performed: Invoice, etc.",
                "readOnly" : true
              }
            },
            "description" : "The object that represents the operation."
          },
          "name" : {
            "type" : "string",
            "description" : "Operation name: {provider}/{resource}/{operation}",
            "readOnly" : true
          }
        },
        "description" : "A Media Services REST API operation"
      },
      "OperationListResult" : {
        "type" : "object",
        "properties" : {
          "nextLink" : {
            "type" : "string",
            "description" : "URL to get the next set of operation list results if there are any.",
            "readOnly" : true
          },
          "value" : {
            "type" : "array",
            "description" : "List of Media Services operations supported by the Microsoft.Media resource provider.",
            "readOnly" : true,
            "items" : {
              "$ref" : "#/components/schemas/Operation"
            }
          }
        },
        "description" : "Result of the request to list Media Services operations."
      },
      "RegenerateKeyInput" : {
        "required" : [ "keyType" ],
        "type" : "object",
        "properties" : {
          "keyType" : {
            "type" : "string",
            "description" : "The keyType indicating which key you want to regenerate, Primary or Secondary.",
            "enum" : [ "Primary", "Secondary" ]
          }
        },
        "description" : "The request body for a RegenerateKey API.",
        "example" : {
          "keyType" : "Primary"
        }
      },
      "RegenerateKeyOutput" : {
        "type" : "object",
        "properties" : {
          "key" : {
            "type" : "string",
            "description" : "The new value of either the primary or secondary key."
          }
        },
        "description" : "The response body for a RegenerateKey API.",
        "example" : {
          "key" : "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx="
        }
      },
      "Resource" : {
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string",
            "description" : "The id of the resource.",
            "readOnly" : true
          },
          "location" : {
            "type" : "string",
            "description" : "The geographic location of the resource. This must be one of the supported and registered Azure Geo Regions (for example, West US, East US, Southeast Asia, and so forth)."
          },
          "name" : {
            "type" : "string",
            "description" : "The name of the resource.",
            "readOnly" : true
          },
          "tags" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "string"
            },
            "description" : "Tags to help categorize the resource in the Azure portal."
          },
          "type" : {
            "type" : "string",
            "description" : "The type of the resource",
            "readOnly" : true
          }
        },
        "description" : "The Azure Resource Manager resource."
      },
      "ResourceType" : {
        "type" : "string",
        "description" : "Type of MediaService resource.",
        "enum" : [ "mediaservices" ]
      },
      "ServiceKeys" : {
        "type" : "object",
        "properties" : {
          "primaryAuthEndpoint" : {
            "type" : "string",
            "description" : "The primary authorization endpoint."
          },
          "primaryKey" : {
            "type" : "string",
            "description" : "The primary key for the Media Service resource."
          },
          "scope" : {
            "type" : "string",
            "description" : "The authorization scope."
          },
          "secondaryAuthEndpoint" : {
            "type" : "string",
            "description" : "The secondary authorization endpoint."
          },
          "secondaryKey" : {
            "type" : "string",
            "description" : "The secondary key for the Media Service resource."
          }
        },
        "description" : "The response body for a ListKeys API.",
        "example" : {
          "primaryAuthEndpoint" : "https://wamsprodglobal001acs.accesscontrol.windows.net/",
          "primaryKey" : "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=",
          "scope" : "urn:windowsazuremediaservices",
          "secondaryAuthEndpoint" : "https://wamsprodglobal002acs.accesscontrol.windows.net/",
          "secondaryKey" : "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx="
        }
      },
      "StorageAccount" : {
        "required" : [ "id", "isPrimary" ],
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string",
            "description" : "The id of the storage account resource. Media Services relies on tables and queues as well as blobs, so the primary storage account must be a Standard Storage account (either Microsoft.ClassicStorage or Microsoft.Storage). Blob only storage accounts can be added as secondary storage accounts (isPrimary false)."
          },
          "isPrimary" : {
            "type" : "boolean",
            "description" : "Is this storage account resource the primary storage account for the Media Service resource. Blob only storage must set this to false."
          }
        },
        "description" : "The properties of a storage account associated with this resource.",
        "example" : {
          "id" : "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/contosoresources/providers/Microsoft.Storage/storageAccounts/contosomedia",
          "isPrimary" : true
        }
      },
      "SyncStorageKeysInput" : {
        "required" : [ "id" ],
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string",
            "description" : "The id of the storage account resource."
          }
        },
        "description" : "The request  body for a SyncStorageKeys API.",
        "example" : {
          "id" : "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/contosoresources/providers/Microsoft.Storage/storageAccounts/contosomedia"
        }
      }
    },
    "parameters" : {
      "apiVersionParameter" : {
        "name" : "api-version",
        "in" : "query",
        "description" : "Version of the API to be used with the client request. The current version is 2015-10-01.",
        "required" : true,
        "schema" : {
          "type" : "string"
        }
      },
      "mediaResourceNameParameter" : {
        "name" : "mediaServiceName",
        "in" : "path",
        "description" : "Name of the Media Service.",
        "required" : true,
        "schema" : {
          "maxLength" : 24,
          "minLength" : 3,
          "pattern" : "^[a-z0-9]{3,24}$",
          "type" : "string"
        }
      },
      "resourceGroupNameParameter" : {
        "name" : "resourceGroupName",
        "in" : "path",
        "description" : "Name of the resource group within the Azure subscription.",
        "required" : true,
        "schema" : {
          "type" : "string"
        }
      },
      "subscriptionIdParameter" : {
        "name" : "subscriptionId",
        "in" : "path",
        "description" : "The unique identifier for a Microsoft Azure subscription.",
        "required" : true,
        "schema" : {
          "type" : "string"
        }
      }
    },
    "securitySchemes" : {
      "azure_auth" : {
        "type" : "oauth2",
        "description" : "Azure Active Directory OAuth2 Flow"
      }
    }
  }
}