{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Flight Check-in Links",
    "description" : "\nBefore using this API, we recommend you read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization-262)** for more information on how to generate an access token.\n\nPlease also be aware that our test environment is based on a subset of the production, to see what is included in test please refer to our **[data collection](https://github.com/amadeus4dev/data-collection)**.",
    "version" : "2.1.2"
  },
  "servers" : [ {
    "url" : "https://test.api.amadeus.com/v2"
  } ],
  "paths" : {
    "/reference-data/urls/checkin-links" : {
      "get" : {
        "tags" : [ "checkin-links" ],
        "summary" : "Lists Check-in URLs.",
        "operationId" : "getCheckinURLs",
        "parameters" : [ {
          "name" : "airlineCode",
          "in" : "query",
          "description" : "Airline code following IATA or ICAO standard - e.g. 1X; AF or ESY\n\n[IATA table codes](http://www.iata.org/publications/Pages/code-search.aspx)\n\n[ICAO airlines table codes](https://en.wikipedia.org/wiki/List_of_airline_codes)\n",
          "required" : true,
          "schema" : {
            "pattern" : "([A-Z]{3}|[A-Z]{2})|([0-9][A-Z])|([A-Z][0-9])",
            "type" : "string"
          },
          "example" : "BA"
        }, {
          "name" : "language",
          "in" : "query",
          "description" : "Check-in page language with one of the following patterns 'languageCode' (e.g. EN) or 'languageCode-IATAcountryCode' (e.g. en-GB). \n\nDefault value is **en-GB** (used when required language is not available or when no value is specified).\n",
          "schema" : {
            "pattern" : "[a-zA-Z]{2}([-][a-zA-Z]{2})?",
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful Operation",
            "content" : {
              "application/vnd.amadeus+json" : {
                "schema" : {
                  "title" : "Success",
                  "required" : [ "data" ],
                  "type" : "object",
                  "properties" : {
                    "data" : {
                      "type" : "array",
                      "items" : {
                        "$ref" : "#/components/schemas/CheckinLink"
                      }
                    },
                    "meta" : {
                      "$ref" : "#/components/schemas/Collection_Meta"
                    },
                    "warnings" : {
                      "type" : "array",
                      "items" : {
                        "$ref" : "#/components/schemas/Issue"
                      }
                    }
                  },
                  "example" : {
                    "data" : [ {
                      "channel" : "All",
                      "href" : "https://www.britishairways.com/travel/managebooking/public/en_ch?&bookingRef={PNR}&lastname={LAST}",
                      "id" : "BAEN-GBAll",
                      "parameters" : {
                        "LAST" : {
                          "description" : "Passenger Last Name",
                          "type" : "string"
                        },
                        "PNR" : {
                          "description" : "Record Locator",
                          "format" : "([a-zA-Z]|[0-9]){6}",
                          "type" : "string"
                        }
                      },
                      "type" : "checkin-link"
                    } ],
                    "meta" : {
                      "count" : 1,
                      "links" : {
                        "self" : "http://test.api.amadeus.com/v2/reference-data/urls/checkin-links?airlineCode=BA"
                      }
                    },
                    "warnings" : [ {
                      "code" : 10151,
                      "detail" : "Language not available for this airline, default language applied",
                      "source" : {
                        "parameter" : "language"
                      },
                      "status" : 200,
                      "title" : "DEFAULT LANGUAGE USED"
                    } ]
                  }
                }
              }
            }
          },
          "400" : {
            "description" : "code    | title                                 \n------- | ------------------------------------- \n477     | INVALID FORMAT\n572     | INVALID OPTION\n32171     | MANDATORY DATA MISSING                      \t     \n",
            "content" : {
              "application/vnd.amadeus+json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Error_400"
                }
              }
            }
          },
          "default" : {
            "description" : "Unexpected Error",
            "content" : {
              "application/vnd.amadeus+json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Error_500"
                }
              }
            }
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "CheckinLink" : {
        "required" : [ "channel", "href", "id", "type" ],
        "type" : "object",
        "properties" : {
          "channel" : {
            "type" : "string",
            "description" : "indicates the type of channel supported by the URL",
            "example" : "Mobile",
            "enum" : [ "Mobile", "Web", "All" ]
          },
          "href" : {
            "type" : "string",
            "description" : "direct URL to the relevant page",
            "format" : "uri"
          },
          "id" : {
            "type" : "string",
            "description" : "identifier of the resource",
            "example" : "1XEN-GBMobile"
          },
          "parameters" : {
            "type" : "object",
            "description" : "list of URL parameters with descriptive information such as description and/or type and/or format"
          },
          "type" : {
            "type" : "string",
            "description" : "the resource name",
            "example" : "checkin-link"
          }
        }
      },
      "Collection_Meta" : {
        "title" : "Collection_Meta",
        "type" : "object",
        "properties" : {
          "count" : {
            "type" : "integer",
            "example" : 1
          },
          "links" : {
            "title" : "CollectionLinks",
            "type" : "object",
            "properties" : {
              "first" : {
                "type" : "string",
                "format" : "uri",
                "example" : "https://test.api.amadeus.com/v1/area/resources?..."
              },
              "last" : {
                "type" : "string",
                "format" : "uri",
                "example" : "https://test.api.amadeus.com/v1/area/resources?..."
              },
              "next" : {
                "type" : "string",
                "format" : "uri",
                "example" : "https://test.api.amadeus.com/v1/area/resources?..."
              },
              "previous" : {
                "type" : "string",
                "format" : "uri",
                "example" : "https://test.api.amadeus.com/v1/area/resources?..."
              },
              "self" : {
                "type" : "string",
                "format" : "uri",
                "example" : "https://test.api.amadeus.com/v1/area/resources?..."
              },
              "up" : {
                "type" : "string",
                "format" : "uri",
                "example" : "https://test.api.amadeus.com/v1/area/resources?..."
              }
            },
            "example" : {
              "self" : "https://test.api.amadeus.com/v1/area/resources?param=value"
            }
          }
        }
      },
      "Error_400" : {
        "required" : [ "errors" ],
        "type" : "object",
        "properties" : {
          "errors" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/Issue"
            }
          }
        },
        "example" : {
          "errors" : [ {
            "code" : 477,
            "detail" : "invalid query parameter format",
            "source" : {
              "example" : "CDG",
              "parameter" : "airport"
            },
            "status" : 400,
            "title" : "INVALID FORMAT"
          } ]
        }
      },
      "Error_500" : {
        "required" : [ "errors" ],
        "type" : "object",
        "properties" : {
          "errors" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/Issue"
            }
          }
        },
        "example" : {
          "errors" : [ {
            "code" : 141,
            "status" : 500,
            "title" : "SYSTEM ERROR HAS OCCURRED"
          } ]
        }
      },
      "Issue" : {
        "type" : "object",
        "properties" : {
          "code" : {
            "type" : "integer",
            "description" : "an application-specific error code",
            "format" : "int64"
          },
          "detail" : {
            "type" : "string",
            "description" : "explanation of the error"
          },
          "source" : {
            "title" : "Issue_Source",
            "type" : "object",
            "properties" : {
              "example" : {
                "type" : "string",
                "description" : "a string indicating an example of the right value"
              },
              "parameter" : {
                "type" : "string",
                "description" : "a string indicating which URI query parameter caused the issue"
              },
              "pointer" : {
                "type" : "string",
                "description" : "a JSON Pointer [RFC6901] to the associated entity in the request document"
              }
            },
            "description" : "an object containing references to the source of the error"
          },
          "status" : {
            "type" : "integer",
            "description" : "the HTTP status code applicable to this error"
          },
          "title" : {
            "type" : "string",
            "description" : "a short summary of the error"
          }
        }
      },
      "Parameter" : {
        "required" : [ "type" ],
        "type" : "object",
        "properties" : {
          "description" : {
            "type" : "string",
            "description" : "parameter descriptive information",
            "example" : "Passenger last name"
          },
          "format" : {
            "type" : "string",
            "description" : "format of the parameter",
            "example" : "([a-zA-Z]|[0-9]){6}"
          },
          "type" : {
            "type" : "string",
            "description" : "type of the parameter",
            "example" : "string"
          }
        }
      }
    },
    "responses" : {
      "400" : {
        "description" : "code    | title                                 \n------- | ------------------------------------- \n477     | INVALID FORMAT\n572     | INVALID OPTION\n32171     | MANDATORY DATA MISSING                      \t     \n",
        "content" : {
          "application/vnd.amadeus+json" : {
            "schema" : {
              "$ref" : "#/components/schemas/Error_400"
            }
          }
        }
      },
      "500" : {
        "description" : "Unexpected Error",
        "content" : {
          "application/vnd.amadeus+json" : {
            "schema" : {
              "$ref" : "#/components/schemas/Error_500"
            }
          }
        }
      },
      "checkin-links" : {
        "description" : "Successful Operation",
        "content" : {
          "application/vnd.amadeus+json" : {
            "schema" : {
              "title" : "Success",
              "required" : [ "data" ],
              "type" : "object",
              "properties" : {
                "data" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/CheckinLink"
                  }
                },
                "meta" : {
                  "$ref" : "#/components/schemas/Collection_Meta"
                },
                "warnings" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/Issue"
                  }
                }
              },
              "example" : {
                "data" : [ {
                  "channel" : "All",
                  "href" : "https://www.britishairways.com/travel/managebooking/public/en_ch?&bookingRef={PNR}&lastname={LAST}",
                  "id" : "BAEN-GBAll",
                  "parameters" : {
                    "LAST" : {
                      "description" : "Passenger Last Name",
                      "type" : "string"
                    },
                    "PNR" : {
                      "description" : "Record Locator",
                      "format" : "([a-zA-Z]|[0-9]){6}",
                      "type" : "string"
                    }
                  },
                  "type" : "checkin-link"
                } ],
                "meta" : {
                  "count" : 1,
                  "links" : {
                    "self" : "http://test.api.amadeus.com/v2/reference-data/urls/checkin-links?airlineCode=BA"
                  }
                },
                "warnings" : [ {
                  "code" : 10151,
                  "detail" : "Language not available for this airline, default language applied",
                  "source" : {
                    "parameter" : "language"
                  },
                  "status" : 200,
                  "title" : "DEFAULT LANGUAGE USED"
                } ]
              }
            }
          }
        }
      }
    }
  }
}