{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Flight Busiest Traveling Period",
    "description" : "\nBefore using this API, we recommend you read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization-262)** for more information on how to generate an access token.\n\nPlease also be aware that our test environment is based on a subset of the production, to see what is included in test please refer to our **[data collection](https://github.com/amadeus4dev/data-collection)**.",
    "version" : "1.0.2"
  },
  "servers" : [ {
    "url" : "https://test.api.amadeus.com/v1"
  } ],
  "paths" : {
    "/travel/analytics/air-traffic/busiest-period" : {
      "get" : {
        "tags" : [ "air-traffic" ],
        "summary" : "Returns a list of air traffic reports.",
        "operationId" : "getAirTraffic",
        "parameters" : [ {
          "name" : "cityCode",
          "in" : "query",
          "description" : "Code for the city following IATA standard. [IATA table codes](http://www.iata.org/publications/Pages/code-search.aspx) - e.g. BOS for Boston",
          "required" : true,
          "schema" : {
            "pattern" : "[A-Za-z]{3}",
            "type" : "string"
          },
          "example" : "MAD"
        }, {
          "name" : "period",
          "in" : "query",
          "description" : "time period (year) of the statistics.\n\nYear for which the statistic are requested following [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)\n",
          "required" : true,
          "schema" : {
            "type" : "string"
          },
          "example" : 2017
        }, {
          "name" : "direction",
          "in" : "query",
          "description" : "Use ARRIVING to have statistics on travelers coming to the city or DEPARTING for statistics on travelers leaving the city.\n\nBy default, statistics are given on travelers ARRIVING the city.\n",
          "schema" : {
            "type" : "string",
            "default" : "ARRIVING",
            "enum" : [ "ARRIVING", "DEPARTING" ]
          },
          "example" : "ARRIVING"
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful Operation",
            "content" : {
              "application/vnd.amadeus+json" : {
                "schema" : {
                  "title" : "Success",
                  "required" : [ "data" ],
                  "type" : "object",
                  "properties" : {
                    "data" : {
                      "type" : "array",
                      "items" : {
                        "$ref" : "#/components/schemas/Air_Traffic"
                      }
                    },
                    "meta" : {
                      "$ref" : "#/components/schemas/Collection_Meta"
                    },
                    "warnings" : {
                      "type" : "array",
                      "items" : {
                        "$ref" : "#/components/schemas/Issue"
                      }
                    }
                  },
                  "example" : {
                    "data" : [ {
                      "analytics" : {
                        "travelers" : {
                          "score" : 9
                        }
                      },
                      "period" : "2017-05",
                      "type" : "air-traffic"
                    }, {
                      "analytics" : {
                        "travelers" : {
                          "score" : 9
                        }
                      },
                      "period" : "2017-12",
                      "type" : "air-traffic"
                    }, {
                      "analytics" : {
                        "travelers" : {
                          "score" : 8
                        }
                      },
                      "period" : "2017-09",
                      "type" : "air-traffic"
                    }, {
                      "analytics" : {
                        "travelers" : {
                          "score" : 8
                        }
                      },
                      "period" : "2017-10",
                      "type" : "air-traffic"
                    }, {
                      "analytics" : {
                        "travelers" : {
                          "score" : 8
                        }
                      },
                      "period" : "2017-07",
                      "type" : "air-traffic"
                    }, {
                      "analytics" : {
                        "travelers" : {
                          "score" : 8
                        }
                      },
                      "period" : "2017-06",
                      "type" : "air-traffic"
                    }, {
                      "analytics" : {
                        "travelers" : {
                          "score" : 8
                        }
                      },
                      "period" : "2017-02",
                      "type" : "air-traffic"
                    }, {
                      "analytics" : {
                        "travelers" : {
                          "score" : 8
                        }
                      },
                      "period" : "2017-03",
                      "type" : "air-traffic"
                    }, {
                      "analytics" : {
                        "travelers" : {
                          "score" : 8
                        }
                      },
                      "period" : "2017-01",
                      "type" : "air-traffic"
                    }, {
                      "analytics" : {
                        "travelers" : {
                          "score" : 8
                        }
                      },
                      "period" : "2017-04",
                      "type" : "air-traffic"
                    }, {
                      "analytics" : {
                        "travelers" : {
                          "score" : 8
                        }
                      },
                      "period" : "2017-08",
                      "type" : "air-traffic"
                    }, {
                      "analytics" : {
                        "travelers" : {
                          "score" : 8
                        }
                      },
                      "period" : "2017-11",
                      "type" : "air-traffic"
                    } ],
                    "meta" : {
                      "count" : 12,
                      "links" : {
                        "self" : "https://test.api.amadeus.com/v1/travel/analytics/air-traffic/busiest-period?cityCode=MAD&direction=ARRIVING&period=2017"
                      }
                    }
                  }
                }
              }
            }
          },
          "400" : {
            "description" : "code    | title                                 \n------- | ------------------------------------- \n477     | INVALID FORMAT\n572     | INVALID OPTION\n2781    | INVALID LENGTH\n4926    | INVALID DATA RECEIVED\n32171   | MANDATORY DATA MISSING\n",
            "content" : {
              "application/vnd.amadeus+json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Error_400"
                }
              }
            }
          },
          "default" : {
            "description" : "Unexpected Error",
            "content" : {
              "application/vnd.amadeus+json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Error_500"
                }
              }
            }
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "Air_Traffic" : {
        "type" : "object",
        "properties" : {
          "analytics" : {
            "$ref" : "#/components/schemas/Analytics"
          },
          "period" : {
            "type" : "string",
            "description" : "Time period following [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) standard",
            "example" : "2017-01"
          },
          "type" : {
            "type" : "string",
            "example" : "air-traffic"
          }
        }
      },
      "Analytics" : {
        "type" : "object",
        "properties" : {
          "travelers" : {
            "$ref" : "#/components/schemas/Travelers"
          }
        }
      },
      "Collection_Meta" : {
        "title" : "Collection_Meta",
        "type" : "object",
        "properties" : {
          "count" : {
            "type" : "integer",
            "example" : 1
          },
          "links" : {
            "title" : "CollectionLinks",
            "type" : "object",
            "properties" : {
              "first" : {
                "type" : "string",
                "format" : "uri",
                "example" : "https://test.api.amadeus.com/v1/area/resources?..."
              },
              "last" : {
                "type" : "string",
                "format" : "uri",
                "example" : "https://test.api.amadeus.com/v1/area/resources?..."
              },
              "next" : {
                "type" : "string",
                "format" : "uri",
                "example" : "https://test.api.amadeus.com/v1/area/resources?..."
              },
              "previous" : {
                "type" : "string",
                "format" : "uri",
                "example" : "https://test.api.amadeus.com/v1/area/resources?..."
              },
              "self" : {
                "type" : "string",
                "format" : "uri",
                "example" : "https://test.api.amadeus.com/v1/area/resources?..."
              },
              "up" : {
                "type" : "string",
                "format" : "uri",
                "example" : "https://test.api.amadeus.com/v1/area/resources?..."
              }
            },
            "example" : {
              "self" : "https://test.api.amadeus.com/v1/area/resources?param=value"
            }
          }
        }
      },
      "Error_400" : {
        "required" : [ "errors" ],
        "type" : "object",
        "properties" : {
          "errors" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/Issue"
            }
          }
        },
        "example" : {
          "errors" : [ {
            "code" : 477,
            "detail" : "invalid query parameter format",
            "source" : {
              "example" : "CDG",
              "parameter" : "airport"
            },
            "status" : 400,
            "title" : "INVALID FORMAT"
          } ]
        }
      },
      "Error_500" : {
        "required" : [ "errors" ],
        "type" : "object",
        "properties" : {
          "errors" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/Issue"
            }
          }
        },
        "example" : {
          "errors" : [ {
            "code" : 141,
            "status" : 500,
            "title" : "SYSTEM ERROR HAS OCCURRED"
          } ]
        }
      },
      "Issue" : {
        "type" : "object",
        "properties" : {
          "code" : {
            "type" : "integer",
            "description" : "an application-specific error code",
            "format" : "int64"
          },
          "detail" : {
            "type" : "string",
            "description" : "explanation of the error"
          },
          "source" : {
            "title" : "Issue_Source",
            "type" : "object",
            "properties" : {
              "example" : {
                "type" : "string",
                "description" : "a string indicating an example of the right value"
              },
              "parameter" : {
                "type" : "string",
                "description" : "a string indicating which URI query parameter caused the issue"
              },
              "pointer" : {
                "type" : "string",
                "description" : "a JSON Pointer [RFC6901] to the associated entity in the request document"
              }
            },
            "description" : "an object containing references to the source of the error"
          },
          "status" : {
            "type" : "integer",
            "description" : "the HTTP status code applicable to this error"
          },
          "title" : {
            "type" : "string",
            "description" : "a short summary of the error"
          }
        }
      },
      "Travelers" : {
        "type" : "object",
        "properties" : {
          "score" : {
            "type" : "number",
            "description" : "Approximate score for ranking purposes calculated based on number of travelers in the location.",
            "format" : "integer",
            "example" : 68.0
          }
        }
      }
    },
    "responses" : {
      "400" : {
        "description" : "code    | title                                 \n------- | ------------------------------------- \n477     | INVALID FORMAT\n572     | INVALID OPTION\n2781    | INVALID LENGTH\n4926    | INVALID DATA RECEIVED\n32171   | MANDATORY DATA MISSING\n",
        "content" : {
          "application/vnd.amadeus+json" : {
            "schema" : {
              "$ref" : "#/components/schemas/Error_400"
            }
          }
        }
      },
      "500" : {
        "description" : "Unexpected Error",
        "content" : {
          "application/vnd.amadeus+json" : {
            "schema" : {
              "$ref" : "#/components/schemas/Error_500"
            }
          }
        }
      },
      "air-traffic" : {
        "description" : "Successful Operation",
        "content" : {
          "application/vnd.amadeus+json" : {
            "schema" : {
              "title" : "Success",
              "required" : [ "data" ],
              "type" : "object",
              "properties" : {
                "data" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/Air_Traffic"
                  }
                },
                "meta" : {
                  "$ref" : "#/components/schemas/Collection_Meta"
                },
                "warnings" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/Issue"
                  }
                }
              },
              "example" : {
                "data" : [ {
                  "analytics" : {
                    "travelers" : {
                      "score" : 9
                    }
                  },
                  "period" : "2017-05",
                  "type" : "air-traffic"
                }, {
                  "analytics" : {
                    "travelers" : {
                      "score" : 9
                    }
                  },
                  "period" : "2017-12",
                  "type" : "air-traffic"
                }, {
                  "analytics" : {
                    "travelers" : {
                      "score" : 8
                    }
                  },
                  "period" : "2017-09",
                  "type" : "air-traffic"
                }, {
                  "analytics" : {
                    "travelers" : {
                      "score" : 8
                    }
                  },
                  "period" : "2017-10",
                  "type" : "air-traffic"
                }, {
                  "analytics" : {
                    "travelers" : {
                      "score" : 8
                    }
                  },
                  "period" : "2017-07",
                  "type" : "air-traffic"
                }, {
                  "analytics" : {
                    "travelers" : {
                      "score" : 8
                    }
                  },
                  "period" : "2017-06",
                  "type" : "air-traffic"
                }, {
                  "analytics" : {
                    "travelers" : {
                      "score" : 8
                    }
                  },
                  "period" : "2017-02",
                  "type" : "air-traffic"
                }, {
                  "analytics" : {
                    "travelers" : {
                      "score" : 8
                    }
                  },
                  "period" : "2017-03",
                  "type" : "air-traffic"
                }, {
                  "analytics" : {
                    "travelers" : {
                      "score" : 8
                    }
                  },
                  "period" : "2017-01",
                  "type" : "air-traffic"
                }, {
                  "analytics" : {
                    "travelers" : {
                      "score" : 8
                    }
                  },
                  "period" : "2017-04",
                  "type" : "air-traffic"
                }, {
                  "analytics" : {
                    "travelers" : {
                      "score" : 8
                    }
                  },
                  "period" : "2017-08",
                  "type" : "air-traffic"
                }, {
                  "analytics" : {
                    "travelers" : {
                      "score" : 8
                    }
                  },
                  "period" : "2017-11",
                  "type" : "air-traffic"
                } ],
                "meta" : {
                  "count" : 12,
                  "links" : {
                    "self" : "https://test.api.amadeus.com/v1/travel/analytics/air-traffic/busiest-period?cityCode=MAD&direction=ARRIVING&period=2017"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}