{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Points of Interest",
    "description" : "\nBefore using this API, we recommend you read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization-262)** for more information on how to generate an access token.\n\nPlease also be aware that our test environment is based on a subset of the production, this API in test only returns a few selected cities. You can find the list in our **[data collection](https://github.com/amadeus4dev/data-collection)**.\n",
    "version" : "1.1.1"
  },
  "servers" : [ {
    "url" : "https://test.api.amadeus.com/v1"
  } ],
  "paths" : {
    "/reference-data/locations/pois" : {
      "get" : {
        "tags" : [ "Search" ],
        "summary" : "Returns points of interest for a given location and radius.",
        "operationId" : "getPointsOfInterest",
        "parameters" : [ {
          "name" : "latitude",
          "in" : "query",
          "description" : "Latitude (decimal coordinates)",
          "required" : true,
          "schema" : {
            "type" : "number",
            "format" : "double"
          },
          "example" : 41.397158
        }, {
          "name" : "longitude",
          "in" : "query",
          "description" : "Longitude (decimal coordinates)",
          "required" : true,
          "schema" : {
            "type" : "number",
            "format" : "double"
          },
          "example" : 2.160873
        }, {
          "name" : "radius",
          "in" : "query",
          "description" : "radius of the search in Kilometer. Can be from 0 to 20, default value is 1 Km.",
          "schema" : {
            "maximum" : 20,
            "minimum" : 0,
            "type" : "integer",
            "default" : 1
          }
        }, {
          "name" : "page[limit]",
          "in" : "query",
          "description" : "maximum items in one page",
          "schema" : {
            "type" : "integer",
            "default" : 10
          }
        }, {
          "name" : "page[offset]",
          "in" : "query",
          "description" : "start index of the requested page",
          "schema" : {
            "type" : "integer",
            "default" : 0
          }
        }, {
          "name" : "categories",
          "in" : "query",
          "description" : "category of the location. \n\nMultiple value can be selected using a comma i.e. SIGHTS, SHOPPING\n",
          "style" : "form",
          "explode" : false,
          "schema" : {
            "type" : "array",
            "items" : {
              "type" : "string",
              "enum" : [ "SIGHTS", "NIGHTLIFE", "RESTAURANT", "SHOPPING" ]
            }
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful Operation",
            "content" : {
              "application/vnd.amadeus+json" : {
                "schema" : {
                  "title" : "Success",
                  "required" : [ "data" ],
                  "type" : "object",
                  "properties" : {
                    "data" : {
                      "type" : "array",
                      "items" : {
                        "$ref" : "#/components/schemas/Location"
                      }
                    },
                    "meta" : {
                      "$ref" : "#/components/schemas/Collection_Meta"
                    }
                  },
                  "example" : {
                    "data" : [ {
                      "category" : "SIGHTS",
                      "geoCode" : {
                        "latitude" : 41.39165,
                        "longitude" : 2.164772
                      },
                      "id" : "9CB40CB5D0",
                      "name" : "Casa Batlló",
                      "rank" : 5,
                      "self" : {
                        "href" : "https://test.api.amadeus.com/v1/reference-data/locations/pois/9CB40CB5D0",
                        "methods" : [ "GET" ]
                      },
                      "subType" : "POINT_OF_INTEREST",
                      "tags" : [ "sightseeing", "sights", "museum", "landmark", "tourguide", "restaurant", "attraction", "activities", "commercialplace", "shopping", "souvenir" ],
                      "type" : "location"
                    }, {
                      "category" : "RESTAURANT",
                      "geoCode" : {
                        "latitude" : 41.397987,
                        "longitude" : 2.161159
                      },
                      "id" : "4690B83DCA",
                      "name" : "La Pepita",
                      "rank" : 30,
                      "self" : {
                        "href" : "https://test.api.amadeus.com/v1/reference-data/locations/pois/4690B83DCA",
                        "methods" : [ "GET" ]
                      },
                      "subType" : "POINT_OF_INTEREST",
                      "tags" : [ "restaurant", "tapas", "pub", "bar", "sightseeing", "commercialplace" ],
                      "type" : "location"
                    }, {
                      "category" : "RESTAURANT",
                      "geoCode" : {
                        "latitude" : 41.38827,
                        "longitude" : 2.161604
                      },
                      "id" : "3EF139D861",
                      "name" : "Brunch & Cake",
                      "rank" : 30,
                      "self" : {
                        "href" : "https://test.api.amadeus.com/v1/reference-data/locations/pois/3EF139D861",
                        "methods" : [ "GET" ]
                      },
                      "subType" : "POINT_OF_INTEREST",
                      "tags" : [ "vegetarian", "restaurant", "breakfast", "shopping", "bakery", "transport", "patio", "garden" ],
                      "type" : "location"
                    }, {
                      "category" : "RESTAURANT",
                      "geoCode" : {
                        "latitude" : 41.392376,
                        "longitude" : 2.160919
                      },
                      "id" : "AB3F122E3E",
                      "name" : "Cervecería Catalana",
                      "rank" : 30,
                      "self" : {
                        "href" : "https://test.api.amadeus.com/v1/reference-data/locations/pois/AB3F122E3E",
                        "methods" : [ "GET" ]
                      },
                      "subType" : "POINT_OF_INTEREST",
                      "tags" : [ "restaurant", "tapas", "sightseeing", "traditionalcuisine", "bar", "activities", "commercialplace" ],
                      "type" : "location"
                    }, {
                      "category" : "RESTAURANT",
                      "geoCode" : {
                        "latitude" : 41.40043,
                        "longitude" : 2.15463
                      },
                      "id" : "752402FCA2",
                      "name" : "Botafumeiro",
                      "rank" : 30,
                      "self" : {
                        "href" : "https://test.api.amadeus.com/v1/reference-data/locations/pois/752402FCA2",
                        "methods" : [ "GET" ]
                      },
                      "subType" : "POINT_OF_INTEREST",
                      "tags" : [ "restaurant", "seafood", "sightseeing", "professionalservices", "transport", "commercialplace" ],
                      "type" : "location"
                    }, {
                      "category" : "SIGHTS",
                      "geoCode" : {
                        "latitude" : 41.39148,
                        "longitude" : 2.164981
                      },
                      "id" : "5F1CED3994",
                      "name" : "Casa Amatller",
                      "rank" : 100,
                      "self" : {
                        "href" : "https://test.api.amadeus.com/v1/reference-data/locations/pois/5F1CED3994",
                        "methods" : [ "GET" ]
                      },
                      "subType" : "POINT_OF_INTEREST",
                      "tags" : [ "sightseeing", "sights", "museum", "landmark", "restaurant", "tourguide", "historicplace", "historic", "attraction", "commercialplace", "activities", "shopping", "events" ],
                      "type" : "location"
                    }, {
                      "category" : "RESTAURANT",
                      "geoCode" : {
                        "latitude" : 41.390785,
                        "longitude" : 2.167414
                      },
                      "id" : "30601A1A90",
                      "name" : "Tapas 24",
                      "rank" : 100,
                      "self" : {
                        "href" : "https://test.api.amadeus.com/v1/reference-data/locations/pois/30601A1A90",
                        "methods" : [ "GET" ]
                      },
                      "subType" : "POINT_OF_INTEREST",
                      "tags" : [ "restaurant", "tapas", "traditionalcuisine", "sightseeing", "commercialplace", "transport", "patio", "garden", "activities", "bar" ],
                      "type" : "location"
                    }, {
                      "category" : "NIGHTLIFE",
                      "geoCode" : {
                        "latitude" : 41.392677,
                        "longitude" : 2.153942
                      },
                      "id" : "15C8B8148C",
                      "name" : "Dry Martini",
                      "rank" : 100,
                      "self" : {
                        "href" : "https://test.api.amadeus.com/v1/reference-data/locations/pois/15C8B8148C",
                        "methods" : [ "GET" ]
                      },
                      "subType" : "POINT_OF_INTEREST",
                      "tags" : [ "bar", "restaurant", "nightlife", "club", "sightseeing", "attraction", "activities" ],
                      "type" : "location"
                    }, {
                      "category" : "RESTAURANT",
                      "geoCode" : {
                        "latitude" : 41.399193,
                        "longitude" : 2.159853
                      },
                      "id" : "BD29CF2CCD",
                      "name" : "Con Gracia",
                      "rank" : 100,
                      "self" : {
                        "href" : "https://test.api.amadeus.com/v1/reference-data/locations/pois/BD29CF2CCD",
                        "methods" : [ "GET" ]
                      },
                      "subType" : "POINT_OF_INTEREST",
                      "tags" : [ "restaurant", "sightseeing", "commercialplace", "professionalservices", "activities" ],
                      "type" : "location"
                    }, {
                      "category" : "RESTAURANT",
                      "geoCode" : {
                        "latitude" : 41.390198,
                        "longitude" : 2.156974
                      },
                      "id" : "24DE6CE737",
                      "name" : "Osmosis",
                      "rank" : 100,
                      "self" : {
                        "href" : "https://test.api.amadeus.com/v1/reference-data/locations/pois/24DE6CE737",
                        "methods" : [ "GET" ]
                      },
                      "subType" : "POINT_OF_INTEREST",
                      "tags" : [ "restaurant", "shopping", "transport", "professionalservices" ],
                      "type" : "location"
                    } ],
                    "meta" : {
                      "count" : 120,
                      "links" : {
                        "first" : "https://test.api.amadeus.com/v1/reference-data/locations/pois?latitude=41.397158&longitude=2.160873&page[offset]=0&page[limit]=10",
                        "last" : "https://test.api.amadeus.com/v1/reference-data/locations/pois?latitude=41.397158&longitude=2.160873&page[offset]=120&page[limit]=10",
                        "next" : "https://test.api.amadeus.com/v1/reference-data/locations/pois?latitude=41.397158&longitude=2.160873&page[offset]=10&page[limit]=10",
                        "self" : "https://test.api.amadeus.com/v1/reference-data/locations/pois?latitude=41.397158&longitude=2.160873",
                        "up" : "https://test.api.amadeus.com/v1/reference-data/locations/pois?latitude=41.397158&longitude=2.160873"
                      }
                    }
                  }
                }
              }
            }
          },
          "400" : {
            "description" : "code    | title                                 \n------- | ------------------------------------- \n477     | INVALID FORMAT\n572     | INVALID OPTION\n4926    | INVALID DATA RECEIVED               \n32171   | MANDATORY DATA MISSING \t     \n",
            "content" : {
              "application/vnd.amadeus+json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Error_400"
                }
              }
            }
          },
          "default" : {
            "description" : "Unexpected Error",
            "content" : {
              "application/vnd.amadeus+json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Error_500"
                }
              }
            }
          }
        }
      }
    },
    "/reference-data/locations/pois/by-square" : {
      "get" : {
        "tags" : [ "Search" ],
        "summary" : "Returns points of interest for a given area",
        "operationId" : "getPointsOfInterestBySquare",
        "parameters" : [ {
          "name" : "north",
          "in" : "query",
          "description" : "Latitude north of bounding box (decimal coordinates)",
          "required" : true,
          "schema" : {
            "type" : "number",
            "format" : "double"
          },
          "example" : 41.397158
        }, {
          "name" : "west",
          "in" : "query",
          "description" : "Longitude west of bounding box (decimal coordinates)",
          "required" : true,
          "schema" : {
            "type" : "number",
            "format" : "double"
          },
          "example" : 2.160873
        }, {
          "name" : "south",
          "in" : "query",
          "description" : "Latitude south of bounding box (decimal coordinates)",
          "required" : true,
          "schema" : {
            "type" : "number",
            "format" : "double"
          },
          "example" : 41.394582
        }, {
          "name" : "east",
          "in" : "query",
          "description" : "Longitude east of bounding box (decimal coordinates)",
          "required" : true,
          "schema" : {
            "type" : "number",
            "format" : "double"
          },
          "example" : 2.177181
        }, {
          "name" : "page[limit]",
          "in" : "query",
          "description" : "maximum items in one page",
          "schema" : {
            "type" : "integer",
            "default" : 10
          }
        }, {
          "name" : "page[offset]",
          "in" : "query",
          "description" : "start index of the requested page",
          "schema" : {
            "type" : "integer",
            "default" : 0
          }
        }, {
          "name" : "categories",
          "in" : "query",
          "description" : "category of the location. \n\nMultiple value can be selected using a comma i.e. SIGHTS, SHOPPING\n",
          "style" : "form",
          "explode" : false,
          "schema" : {
            "type" : "array",
            "items" : {
              "type" : "string",
              "enum" : [ "SIGHTS", "NIGHTLIFE", "RESTAURANT", "SHOPPING" ]
            }
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful Operation",
            "content" : {
              "application/vnd.amadeus+json" : {
                "schema" : {
                  "title" : "Success",
                  "required" : [ "data" ],
                  "type" : "object",
                  "properties" : {
                    "data" : {
                      "type" : "array",
                      "items" : {
                        "$ref" : "#/components/schemas/Location"
                      }
                    },
                    "meta" : {
                      "$ref" : "#/components/schemas/Collection_Meta"
                    }
                  },
                  "example" : {
                    "data" : [ {
                      "category" : "SIGHTS",
                      "geoCode" : {
                        "latitude" : 41.39165,
                        "longitude" : 2.164772
                      },
                      "id" : "9CB40CB5D0",
                      "name" : "Casa Batlló",
                      "rank" : 5,
                      "self" : {
                        "href" : "https://test.api.amadeus.com/v1/reference-data/locations/pois/9CB40CB5D0",
                        "methods" : [ "GET" ]
                      },
                      "subType" : "POINT_OF_INTEREST",
                      "tags" : [ "sightseeing", "sights", "museum", "landmark", "tourguide", "restaurant", "attraction", "activities", "commercialplace", "shopping", "souvenir" ],
                      "type" : "location"
                    }, {
                      "category" : "RESTAURANT",
                      "geoCode" : {
                        "latitude" : 41.397987,
                        "longitude" : 2.161159
                      },
                      "id" : "4690B83DCA",
                      "name" : "La Pepita",
                      "rank" : 30,
                      "self" : {
                        "href" : "https://test.api.amadeus.com/v1/reference-data/locations/pois/4690B83DCA",
                        "methods" : [ "GET" ]
                      },
                      "subType" : "POINT_OF_INTEREST",
                      "tags" : [ "restaurant", "tapas", "pub", "bar", "sightseeing", "commercialplace" ],
                      "type" : "location"
                    }, {
                      "category" : "RESTAURANT",
                      "geoCode" : {
                        "latitude" : 41.38827,
                        "longitude" : 2.161604
                      },
                      "id" : "3EF139D861",
                      "name" : "Brunch & Cake",
                      "rank" : 30,
                      "self" : {
                        "href" : "https://test.api.amadeus.com/v1/reference-data/locations/pois/3EF139D861",
                        "methods" : [ "GET" ]
                      },
                      "subType" : "POINT_OF_INTEREST",
                      "tags" : [ "vegetarian", "restaurant", "breakfast", "shopping", "bakery", "transport", "patio", "garden" ],
                      "type" : "location"
                    }, {
                      "category" : "RESTAURANT",
                      "geoCode" : {
                        "latitude" : 41.392376,
                        "longitude" : 2.160919
                      },
                      "id" : "AB3F122E3E",
                      "name" : "Cervecería Catalana",
                      "rank" : 30,
                      "self" : {
                        "href" : "https://test.api.amadeus.com/v1/reference-data/locations/pois/AB3F122E3E",
                        "methods" : [ "GET" ]
                      },
                      "subType" : "POINT_OF_INTEREST",
                      "tags" : [ "restaurant", "tapas", "sightseeing", "traditionalcuisine", "bar", "activities", "commercialplace" ],
                      "type" : "location"
                    }, {
                      "category" : "RESTAURANT",
                      "geoCode" : {
                        "latitude" : 41.40043,
                        "longitude" : 2.15463
                      },
                      "id" : "752402FCA2",
                      "name" : "Botafumeiro",
                      "rank" : 30,
                      "self" : {
                        "href" : "https://test.api.amadeus.com/v1/reference-data/locations/pois/752402FCA2",
                        "methods" : [ "GET" ]
                      },
                      "subType" : "POINT_OF_INTEREST",
                      "tags" : [ "restaurant", "seafood", "sightseeing", "professionalservices", "transport", "commercialplace" ],
                      "type" : "location"
                    }, {
                      "category" : "SIGHTS",
                      "geoCode" : {
                        "latitude" : 41.39148,
                        "longitude" : 2.164981
                      },
                      "id" : "5F1CED3994",
                      "name" : "Casa Amatller",
                      "rank" : 100,
                      "self" : {
                        "href" : "https://test.api.amadeus.com/v1/reference-data/locations/pois/5F1CED3994",
                        "methods" : [ "GET" ]
                      },
                      "subType" : "POINT_OF_INTEREST",
                      "tags" : [ "sightseeing", "sights", "museum", "landmark", "restaurant", "tourguide", "historicplace", "historic", "attraction", "commercialplace", "activities", "shopping", "events" ],
                      "type" : "location"
                    }, {
                      "category" : "RESTAURANT",
                      "geoCode" : {
                        "latitude" : 41.390785,
                        "longitude" : 2.167414
                      },
                      "id" : "30601A1A90",
                      "name" : "Tapas 24",
                      "rank" : 100,
                      "self" : {
                        "href" : "https://test.api.amadeus.com/v1/reference-data/locations/pois/30601A1A90",
                        "methods" : [ "GET" ]
                      },
                      "subType" : "POINT_OF_INTEREST",
                      "tags" : [ "restaurant", "tapas", "traditionalcuisine", "sightseeing", "commercialplace", "transport", "patio", "garden", "activities", "bar" ],
                      "type" : "location"
                    }, {
                      "category" : "NIGHTLIFE",
                      "geoCode" : {
                        "latitude" : 41.392677,
                        "longitude" : 2.153942
                      },
                      "id" : "15C8B8148C",
                      "name" : "Dry Martini",
                      "rank" : 100,
                      "self" : {
                        "href" : "https://test.api.amadeus.com/v1/reference-data/locations/pois/15C8B8148C",
                        "methods" : [ "GET" ]
                      },
                      "subType" : "POINT_OF_INTEREST",
                      "tags" : [ "bar", "restaurant", "nightlife", "club", "sightseeing", "attraction", "activities" ],
                      "type" : "location"
                    }, {
                      "category" : "RESTAURANT",
                      "geoCode" : {
                        "latitude" : 41.399193,
                        "longitude" : 2.159853
                      },
                      "id" : "BD29CF2CCD",
                      "name" : "Con Gracia",
                      "rank" : 100,
                      "self" : {
                        "href" : "https://test.api.amadeus.com/v1/reference-data/locations/pois/BD29CF2CCD",
                        "methods" : [ "GET" ]
                      },
                      "subType" : "POINT_OF_INTEREST",
                      "tags" : [ "restaurant", "sightseeing", "commercialplace", "professionalservices", "activities" ],
                      "type" : "location"
                    }, {
                      "category" : "RESTAURANT",
                      "geoCode" : {
                        "latitude" : 41.390198,
                        "longitude" : 2.156974
                      },
                      "id" : "24DE6CE737",
                      "name" : "Osmosis",
                      "rank" : 100,
                      "self" : {
                        "href" : "https://test.api.amadeus.com/v1/reference-data/locations/pois/24DE6CE737",
                        "methods" : [ "GET" ]
                      },
                      "subType" : "POINT_OF_INTEREST",
                      "tags" : [ "restaurant", "shopping", "transport", "professionalservices" ],
                      "type" : "location"
                    } ],
                    "meta" : {
                      "count" : 120,
                      "links" : {
                        "first" : "https://test.api.amadeus.com/v1/reference-data/locations/pois?latitude=41.397158&longitude=2.160873&page[offset]=0&page[limit]=10",
                        "last" : "https://test.api.amadeus.com/v1/reference-data/locations/pois?latitude=41.397158&longitude=2.160873&page[offset]=120&page[limit]=10",
                        "next" : "https://test.api.amadeus.com/v1/reference-data/locations/pois?latitude=41.397158&longitude=2.160873&page[offset]=10&page[limit]=10",
                        "self" : "https://test.api.amadeus.com/v1/reference-data/locations/pois?latitude=41.397158&longitude=2.160873",
                        "up" : "https://test.api.amadeus.com/v1/reference-data/locations/pois?latitude=41.397158&longitude=2.160873"
                      }
                    }
                  }
                }
              }
            }
          },
          "400" : {
            "description" : "code    | title                                 \n------- | ------------------------------------- \n477     | INVALID FORMAT\n572     | INVALID OPTION\n4926    | INVALID DATA RECEIVED               \n32171   | MANDATORY DATA MISSING \t     \n",
            "content" : {
              "application/vnd.amadeus+json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Error_400"
                }
              }
            }
          },
          "default" : {
            "description" : "Unexpected Error",
            "content" : {
              "application/vnd.amadeus+json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Error_500"
                }
              }
            }
          }
        }
      }
    },
    "/reference-data/locations/pois/{poisId}" : {
      "get" : {
        "tags" : [ "Retrieve" ],
        "summary" : "Retieve one point of interest by its Id.",
        "operationId" : "getPointOfInterest",
        "parameters" : [ {
          "name" : "poisId",
          "in" : "path",
          "description" : "identifier of the pois",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful Operation",
            "content" : {
              "application/vnd.amadeus+json" : {
                "schema" : {
                  "title" : "Success",
                  "required" : [ "data" ],
                  "type" : "object",
                  "properties" : {
                    "data" : {
                      "$ref" : "#/components/schemas/Location"
                    },
                    "meta" : {
                      "$ref" : "#/components/schemas/Collection_Meta"
                    }
                  },
                  "example" : {
                    "data" : {
                      "category" : "SIGHTS",
                      "geoCode" : {
                        "latitude" : 41.39165,
                        "longitude" : 2.164772
                      },
                      "id" : "9CB40CB5D0",
                      "name" : "Casa Batlló",
                      "rank" : 1,
                      "self" : {
                        "href" : "https://test.api.amadeus.com/v1/reference-data/locations/pois/9CB40CB5D0",
                        "methods" : [ "GET" ]
                      },
                      "subType" : "POINT_OF_INTEREST",
                      "tags" : [ "sightseeing", "sights", "museum", "landmark", "tourguide", "restaurant", "attraction", "activities", "commercialplace", "shopping", "souvenir" ],
                      "type" : "location"
                    }
                  }
                }
              }
            }
          },
          "400" : {
            "description" : "code    | title                                 \n------- | ------------------------------------- \n477     | INVALID FORMAT\n572     | INVALID OPTION\n4926    | INVALID DATA RECEIVED               \n32171   | MANDATORY DATA MISSING \t     \n",
            "content" : {
              "application/vnd.amadeus+json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Error_400"
                }
              }
            }
          },
          "404" : {
            "description" : "Not Found",
            "content" : {
              "application/vnd.amadeus+json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Error_404"
                }
              }
            }
          },
          "default" : {
            "description" : "Unexpected Error",
            "content" : {
              "application/vnd.amadeus+json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Error_500"
                }
              }
            }
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "Collection_Meta" : {
        "title" : "Collection_Meta",
        "type" : "object",
        "properties" : {
          "count" : {
            "type" : "integer",
            "example" : 1
          },
          "links" : {
            "title" : "CollectionLinks",
            "type" : "object",
            "properties" : {
              "first" : {
                "type" : "string",
                "format" : "uri",
                "example" : "https://test.api.amadeus.com/v1/area/resources?..."
              },
              "last" : {
                "type" : "string",
                "format" : "uri",
                "example" : "https://test.api.amadeus.com/v1/area/resources?..."
              },
              "next" : {
                "type" : "string",
                "format" : "uri",
                "example" : "https://test.api.amadeus.com/v1/area/resources?..."
              },
              "previous" : {
                "type" : "string",
                "format" : "uri",
                "example" : "https://test.api.amadeus.com/v1/area/resources?..."
              },
              "self" : {
                "type" : "string",
                "format" : "uri",
                "example" : "https://test.api.amadeus.com/v1/area/resources?..."
              },
              "up" : {
                "type" : "string",
                "format" : "uri",
                "example" : "https://test.api.amadeus.com/v1/area/resources?..."
              }
            },
            "example" : {
              "self" : "https://test.api.amadeus.com/v1/area/resources?param=value"
            }
          }
        }
      },
      "Error_400" : {
        "required" : [ "errors" ],
        "type" : "object",
        "properties" : {
          "errors" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/Issue"
            }
          }
        },
        "example" : {
          "errors" : [ {
            "code" : 477,
            "detail" : "invalid query parameter format",
            "source" : {
              "example" : "CDG",
              "parameter" : "airport"
            },
            "status" : 400,
            "title" : "INVALID FORMAT"
          } ]
        }
      },
      "Error_404" : {
        "required" : [ "errors" ],
        "type" : "object",
        "properties" : {
          "errors" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/Issue"
            }
          }
        },
        "example" : {
          "errors" : [ {
            "code" : 1797,
            "detail" : "no response found for this query parameter",
            "source" : {
              "parameter" : "airport"
            },
            "status" : 404,
            "title" : "NOT FOUND"
          } ]
        }
      },
      "Error_500" : {
        "required" : [ "errors" ],
        "type" : "object",
        "properties" : {
          "errors" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/Issue"
            }
          }
        },
        "example" : {
          "errors" : [ {
            "code" : 141,
            "status" : 500,
            "title" : "SYSTEM ERROR HAS OCCURRED"
          } ]
        }
      },
      "GeoCode" : {
        "type" : "object",
        "properties" : {
          "latitude" : {
            "type" : "number",
            "description" : "latitude of the location",
            "format" : "double",
            "example" : 43.580418
          },
          "longitude" : {
            "type" : "number",
            "description" : "longitude of the location",
            "format" : "double",
            "example" : 7.125102
          }
        }
      },
      "Issue" : {
        "type" : "object",
        "properties" : {
          "code" : {
            "type" : "integer",
            "description" : "an application-specific error code",
            "format" : "int64"
          },
          "detail" : {
            "type" : "string",
            "description" : "explanation of the error"
          },
          "source" : {
            "title" : "Issue_Source",
            "type" : "object",
            "properties" : {
              "example" : {
                "type" : "string",
                "description" : "a string indicating an example of the right value"
              },
              "parameter" : {
                "type" : "string",
                "description" : "a string indicating which URI query parameter caused the issue"
              },
              "pointer" : {
                "type" : "string",
                "description" : "a JSON Pointer [RFC6901] to the associated entity in the request document"
              }
            },
            "description" : "an object containing references to the source of the error"
          },
          "status" : {
            "type" : "integer",
            "description" : "the HTTP status code applicable to this error"
          },
          "title" : {
            "type" : "string",
            "description" : "a short summary of the error"
          }
        }
      },
      "Links" : {
        "type" : "object",
        "properties" : {
          "href" : {
            "type" : "string",
            "format" : "uri"
          },
          "methods" : {
            "type" : "array",
            "items" : {
              "type" : "string",
              "enum" : [ "GET", "PUT", "DELETE", "POST", "PATCH" ]
            }
          }
        },
        "example" : {
          "href" : "string"
        }
      },
      "Location" : {
        "type" : "object",
        "properties" : {
          "category" : {
            "type" : "string",
            "description" : "category of the location",
            "example" : "HISTORICAL",
            "enum" : [ "SIGHTS", "BEACH_PARK", "HISTORICAL", "NIGHTLIFE", "RESTAURANT", "SHOPPING" ]
          },
          "geoCode" : {
            "$ref" : "#/components/schemas/GeoCode"
          },
          "id" : {
            "type" : "string",
            "description" : "id of the ressource"
          },
          "name" : {
            "type" : "string",
            "description" : "short name of the location",
            "example" : "Paris CDG"
          },
          "rank" : {
            "type" : "string",
            "description" : "the rank is the position compared to other locations based on how famous is a place. 1 being the highest.",
            "example" : "1"
          },
          "self" : {
            "$ref" : "#/components/schemas/Links"
          },
          "subType" : {
            "type" : "string",
            "description" : "location sub type",
            "example" : "AIRPORT",
            "enum" : [ "AIRPORT", "CITY", "POINT_OF_INTEREST", "DISTRICT" ]
          },
          "tags" : {
            "type" : "array",
            "description" : "list of tags related to the location",
            "items" : {
              "type" : "string",
              "example" : ""
            }
          },
          "type" : {
            "type" : "string",
            "description" : "the resource name",
            "example" : "location"
          }
        }
      }
    },
    "responses" : {
      "400" : {
        "description" : "code    | title                                 \n------- | ------------------------------------- \n477     | INVALID FORMAT\n572     | INVALID OPTION\n4926    | INVALID DATA RECEIVED               \n32171   | MANDATORY DATA MISSING \t     \n",
        "content" : {
          "application/vnd.amadeus+json" : {
            "schema" : {
              "$ref" : "#/components/schemas/Error_400"
            }
          }
        }
      },
      "404" : {
        "description" : "Not Found",
        "content" : {
          "application/vnd.amadeus+json" : {
            "schema" : {
              "$ref" : "#/components/schemas/Error_404"
            }
          }
        }
      },
      "500" : {
        "description" : "Unexpected Error",
        "content" : {
          "application/vnd.amadeus+json" : {
            "schema" : {
              "$ref" : "#/components/schemas/Error_500"
            }
          }
        }
      },
      "point-of-interest" : {
        "description" : "Successful Operation",
        "content" : {
          "application/vnd.amadeus+json" : {
            "schema" : {
              "title" : "Success",
              "required" : [ "data" ],
              "type" : "object",
              "properties" : {
                "data" : {
                  "$ref" : "#/components/schemas/Location"
                },
                "meta" : {
                  "$ref" : "#/components/schemas/Collection_Meta"
                }
              },
              "example" : {
                "data" : {
                  "category" : "SIGHTS",
                  "geoCode" : {
                    "latitude" : 41.39165,
                    "longitude" : 2.164772
                  },
                  "id" : "9CB40CB5D0",
                  "name" : "Casa Batlló",
                  "rank" : 1,
                  "self" : {
                    "href" : "https://test.api.amadeus.com/v1/reference-data/locations/pois/9CB40CB5D0",
                    "methods" : [ "GET" ]
                  },
                  "subType" : "POINT_OF_INTEREST",
                  "tags" : [ "sightseeing", "sights", "museum", "landmark", "tourguide", "restaurant", "attraction", "activities", "commercialplace", "shopping", "souvenir" ],
                  "type" : "location"
                }
              }
            }
          }
        }
      },
      "points-of-interest" : {
        "description" : "Successful Operation",
        "content" : {
          "application/vnd.amadeus+json" : {
            "schema" : {
              "title" : "Success",
              "required" : [ "data" ],
              "type" : "object",
              "properties" : {
                "data" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/Location"
                  }
                },
                "meta" : {
                  "$ref" : "#/components/schemas/Collection_Meta"
                }
              },
              "example" : {
                "data" : [ {
                  "category" : "SIGHTS",
                  "geoCode" : {
                    "latitude" : 41.39165,
                    "longitude" : 2.164772
                  },
                  "id" : "9CB40CB5D0",
                  "name" : "Casa Batlló",
                  "rank" : 5,
                  "self" : {
                    "href" : "https://test.api.amadeus.com/v1/reference-data/locations/pois/9CB40CB5D0",
                    "methods" : [ "GET" ]
                  },
                  "subType" : "POINT_OF_INTEREST",
                  "tags" : [ "sightseeing", "sights", "museum", "landmark", "tourguide", "restaurant", "attraction", "activities", "commercialplace", "shopping", "souvenir" ],
                  "type" : "location"
                }, {
                  "category" : "RESTAURANT",
                  "geoCode" : {
                    "latitude" : 41.397987,
                    "longitude" : 2.161159
                  },
                  "id" : "4690B83DCA",
                  "name" : "La Pepita",
                  "rank" : 30,
                  "self" : {
                    "href" : "https://test.api.amadeus.com/v1/reference-data/locations/pois/4690B83DCA",
                    "methods" : [ "GET" ]
                  },
                  "subType" : "POINT_OF_INTEREST",
                  "tags" : [ "restaurant", "tapas", "pub", "bar", "sightseeing", "commercialplace" ],
                  "type" : "location"
                }, {
                  "category" : "RESTAURANT",
                  "geoCode" : {
                    "latitude" : 41.38827,
                    "longitude" : 2.161604
                  },
                  "id" : "3EF139D861",
                  "name" : "Brunch & Cake",
                  "rank" : 30,
                  "self" : {
                    "href" : "https://test.api.amadeus.com/v1/reference-data/locations/pois/3EF139D861",
                    "methods" : [ "GET" ]
                  },
                  "subType" : "POINT_OF_INTEREST",
                  "tags" : [ "vegetarian", "restaurant", "breakfast", "shopping", "bakery", "transport", "patio", "garden" ],
                  "type" : "location"
                }, {
                  "category" : "RESTAURANT",
                  "geoCode" : {
                    "latitude" : 41.392376,
                    "longitude" : 2.160919
                  },
                  "id" : "AB3F122E3E",
                  "name" : "Cervecería Catalana",
                  "rank" : 30,
                  "self" : {
                    "href" : "https://test.api.amadeus.com/v1/reference-data/locations/pois/AB3F122E3E",
                    "methods" : [ "GET" ]
                  },
                  "subType" : "POINT_OF_INTEREST",
                  "tags" : [ "restaurant", "tapas", "sightseeing", "traditionalcuisine", "bar", "activities", "commercialplace" ],
                  "type" : "location"
                }, {
                  "category" : "RESTAURANT",
                  "geoCode" : {
                    "latitude" : 41.40043,
                    "longitude" : 2.15463
                  },
                  "id" : "752402FCA2",
                  "name" : "Botafumeiro",
                  "rank" : 30,
                  "self" : {
                    "href" : "https://test.api.amadeus.com/v1/reference-data/locations/pois/752402FCA2",
                    "methods" : [ "GET" ]
                  },
                  "subType" : "POINT_OF_INTEREST",
                  "tags" : [ "restaurant", "seafood", "sightseeing", "professionalservices", "transport", "commercialplace" ],
                  "type" : "location"
                }, {
                  "category" : "SIGHTS",
                  "geoCode" : {
                    "latitude" : 41.39148,
                    "longitude" : 2.164981
                  },
                  "id" : "5F1CED3994",
                  "name" : "Casa Amatller",
                  "rank" : 100,
                  "self" : {
                    "href" : "https://test.api.amadeus.com/v1/reference-data/locations/pois/5F1CED3994",
                    "methods" : [ "GET" ]
                  },
                  "subType" : "POINT_OF_INTEREST",
                  "tags" : [ "sightseeing", "sights", "museum", "landmark", "restaurant", "tourguide", "historicplace", "historic", "attraction", "commercialplace", "activities", "shopping", "events" ],
                  "type" : "location"
                }, {
                  "category" : "RESTAURANT",
                  "geoCode" : {
                    "latitude" : 41.390785,
                    "longitude" : 2.167414
                  },
                  "id" : "30601A1A90",
                  "name" : "Tapas 24",
                  "rank" : 100,
                  "self" : {
                    "href" : "https://test.api.amadeus.com/v1/reference-data/locations/pois/30601A1A90",
                    "methods" : [ "GET" ]
                  },
                  "subType" : "POINT_OF_INTEREST",
                  "tags" : [ "restaurant", "tapas", "traditionalcuisine", "sightseeing", "commercialplace", "transport", "patio", "garden", "activities", "bar" ],
                  "type" : "location"
                }, {
                  "category" : "NIGHTLIFE",
                  "geoCode" : {
                    "latitude" : 41.392677,
                    "longitude" : 2.153942
                  },
                  "id" : "15C8B8148C",
                  "name" : "Dry Martini",
                  "rank" : 100,
                  "self" : {
                    "href" : "https://test.api.amadeus.com/v1/reference-data/locations/pois/15C8B8148C",
                    "methods" : [ "GET" ]
                  },
                  "subType" : "POINT_OF_INTEREST",
                  "tags" : [ "bar", "restaurant", "nightlife", "club", "sightseeing", "attraction", "activities" ],
                  "type" : "location"
                }, {
                  "category" : "RESTAURANT",
                  "geoCode" : {
                    "latitude" : 41.399193,
                    "longitude" : 2.159853
                  },
                  "id" : "BD29CF2CCD",
                  "name" : "Con Gracia",
                  "rank" : 100,
                  "self" : {
                    "href" : "https://test.api.amadeus.com/v1/reference-data/locations/pois/BD29CF2CCD",
                    "methods" : [ "GET" ]
                  },
                  "subType" : "POINT_OF_INTEREST",
                  "tags" : [ "restaurant", "sightseeing", "commercialplace", "professionalservices", "activities" ],
                  "type" : "location"
                }, {
                  "category" : "RESTAURANT",
                  "geoCode" : {
                    "latitude" : 41.390198,
                    "longitude" : 2.156974
                  },
                  "id" : "24DE6CE737",
                  "name" : "Osmosis",
                  "rank" : 100,
                  "self" : {
                    "href" : "https://test.api.amadeus.com/v1/reference-data/locations/pois/24DE6CE737",
                    "methods" : [ "GET" ]
                  },
                  "subType" : "POINT_OF_INTEREST",
                  "tags" : [ "restaurant", "shopping", "transport", "professionalservices" ],
                  "type" : "location"
                } ],
                "meta" : {
                  "count" : 120,
                  "links" : {
                    "first" : "https://test.api.amadeus.com/v1/reference-data/locations/pois?latitude=41.397158&longitude=2.160873&page[offset]=0&page[limit]=10",
                    "last" : "https://test.api.amadeus.com/v1/reference-data/locations/pois?latitude=41.397158&longitude=2.160873&page[offset]=120&page[limit]=10",
                    "next" : "https://test.api.amadeus.com/v1/reference-data/locations/pois?latitude=41.397158&longitude=2.160873&page[offset]=10&page[limit]=10",
                    "self" : "https://test.api.amadeus.com/v1/reference-data/locations/pois?latitude=41.397158&longitude=2.160873",
                    "up" : "https://test.api.amadeus.com/v1/reference-data/locations/pois?latitude=41.397158&longitude=2.160873"
                  }
                }
              }
            }
          }
        }
      }
    },
    "parameters" : {
      "categories" : {
        "name" : "categories",
        "in" : "query",
        "description" : "category of the location. \n\nMultiple value can be selected using a comma i.e. SIGHTS, SHOPPING\n",
        "style" : "form",
        "explode" : false,
        "schema" : {
          "type" : "array",
          "items" : {
            "type" : "string",
            "enum" : [ "SIGHTS", "NIGHTLIFE", "RESTAURANT", "SHOPPING" ]
          }
        }
      },
      "pageLimit" : {
        "name" : "page[limit]",
        "in" : "query",
        "description" : "maximum items in one page",
        "schema" : {
          "type" : "integer",
          "default" : 10
        }
      },
      "pageOffset" : {
        "name" : "page[offset]",
        "in" : "query",
        "description" : "start index of the requested page",
        "schema" : {
          "type" : "integer",
          "default" : 0
        }
      },
      "poisId" : {
        "name" : "poisId",
        "in" : "path",
        "description" : "identifier of the pois",
        "required" : true,
        "schema" : {
          "type" : "string"
        },
        "example" : "9CB40CB5D0"
      }
    }
  }
}